language: emacs-lisp
cache:
  - directories:
      # Cache stable Emacs binaries (saves 1min per job)
      - "$HOME/emacs/"

env:
  - "CHECK_TARGET=check-core  LISP=sbcl  EMACS_VERSION=25.2"
  # - "CHECK_TARGET=check-core  LISP=cmucl EMACS_VERSION=25.2"
  - "CHECK_TARGET=check-core  LISP=ccl   EMACS_VERSION=25.2"
  - "CHECK_TARGET=check-fancy LISP=sbcl  EMACS_VERSION=25.2"
  # - "CHECK_TARGET=check-fancy LISP=cmucl EMACS_VERSION=25.2"
  - "CHECK_TARGET=check-fancy LISP=ccl   EMACS_VERSION=25.2"
  - "CHECK_TARGET=check-mrepl LISP=sbcl EMACS_VERSION=25.2"
  - "CHECK_TARGET=check-indentation LISP=sbcl EMACS_VERSION=25.2"

before_install:
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  - make LISP=$LISP EMACS=$HOME/emacs/$EMACS_VERSION/src/emacs $CHECK_TARGET
